import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/settings_provider.dart';

class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  static final Map<String, Map<String, String>> _localizedValues = {
    'Italiano': {
      'app_title': 'Evolve',
      'Impostazioni App': 'Impostazioni App',
      'ASPETTO & VISUAL': 'ASPETTO & VISUAL',
      'Modalità Scura': 'Modalità Scura',
      'Colore Accento': 'Colore Accento',
      'CALENDARIO & DASHBOARD': 'CALENDARIO & DASHBOARD',
      'Vista Predefinita': 'Vista Predefinita',
      'ESPERIENZA UTENTE': 'ESPERIENZA UTENTE',
      'Feedback Aptico': 'Feedback Aptico',
      'UNITÀ E LINGUA': 'UNITÀ E LINGUA',
      'Lingua': 'Lingua',
      'Formato 24h': 'Formato 24h',
      'AI & SISTEMA': 'AI & SISTEMA',
      'Suggerimenti AI': 'Suggerimenti AI',
      'Analisi intelligente delle abitudini': 'Analisi intelligente delle abitudini',
      'PRO ONLY': 'Questa funzione è disponibile solo per utenti PRO',
      'Home': 'Home',
      'Statistiche': 'Statistiche',
      'Obiettivi': 'Obiettivi',
      'Salva': 'Salva',
      'Annulla': 'Annulla',
      'Conferma': 'Conferma',
      'Aggiorna Stato Giornaliero': 'Aggiorna Stato Giornaliero',
      'Check-in Giornaliero': 'Check-in Giornaliero',
      'Oggi': 'Oggi',
      'Abitudini': 'Abitudini',
      'Umore': 'Umore',
      'Energia': 'Energia',
      'AI Chat': 'AI Chat',
      'Morning Brief': 'Morning Brief',
      'Review Serale': 'Review Serale',
      'Notifiche': 'Notifiche',
      'Privacy e Sicurezza': 'Privacy e Sicurezza',
      'Account': 'Account',
      'Piano PRO': 'Piano PRO',
      'Informazioni Personali': 'Informazioni Personali',
      'Blocco Biometrico': 'Blocco Biometrico',
      'Analytics Anonimi': 'Analytics Anonimi',
      'Promemoria Abitudini': 'Promemoria Abitudini',
      'Scadenze Obiettivi': 'Scadenze Obiettivi',
      'Insight AI': 'Insight AI',
      'Resoconti Settimanali': 'Resoconti Settimanali',
      'Modalità Focus': 'Modalità Focus',
      'Milestones': 'Milestones',
      'Deep Work Insights': 'Deep Work Insights',
      'Gestione Abitudini': 'Gestione Abitudini',
      'Aggiungi Abitudine': 'Aggiungi Abitudine',
      'Modifica Abitudine': 'Modifica Abitudine',
      'Elimina Abitudine': 'Elimina Abitudine',
      'Nome Abitudine': 'Nome Abitudine',
      'Colore': 'Colore',
      'Trascina per riordinare': 'Trascina per riordinare',
      'Nessuna abitudine tracciata oggi': 'Nessuna abitudine tracciata oggi',
      'Panoramica Statistiche': 'Panoramica Statistiche',
      'Mese': 'Mese',
      'Settimana': 'Settimana',
      'Anno': 'Anno',
      'Vita': 'Vita',
      'Analisi dettagliata delle tue performance.': 'Analisi dettagliata delle tue performance.',
      'Tutti gli Habits': 'Tutte le abitudini',
      'SELEZIONA HABIT': 'SELEZIONA HABIT',
      'Info': 'Info',
      'Trend': 'Trend',
      'Alert': 'Alert',
      'Stats': 'Stats',
      'Completamento': 'Completamento',
      'Globale': 'Globale',
      'Miglior Serie': 'Miglior Serie',
      'Giorni': 'Giorni',
      'Top Performer': 'Top Performer',
      'Giorno Critico': 'Giorno Critico',
      'Focus richiesto': 'Focus richiesto',
      'Abitudini Chiave': 'Abitudini Chiave',
      'Abitudini che influenzano positivamente molte altre': 'Abitudini che influenzano positivamente molte altre',
      'Alto Impatto': 'Alto Impatto',
      'connessioni': 'connessioni',
      'Media Impatto': 'Media Impatto',
      'Analisi Correlazioni': 'Analisi Correlazioni',
      'Pattern tra le tue abitudini': 'Pattern tra le tue abitudini',
      'Coppie Analizzate': 'Coppie Analizzate',
      'Correlazione Media': 'Correlazione Media',
      'Positive': 'Positive',
      'Negative': 'Negative',
      'Abitudini Isolate': 'Abitudini Isolate',
      'Non hanno correlazioni significative.': 'Non hanno correlazioni significative.',
      'Correlazioni Positive': 'Correlazioni Positive',
      'Correlazioni Negative': 'Correlazioni Negative',
      'Attività Recente': 'Attività Recente',
      'Suggerimento': 'Suggerimento',
      'Le abitudini chiave hanno un effetto "domino".': 'Le abitudini chiave hanno un effetto "domino".',
      'timeframe_week_short': 'Sett',
      'timeframe_month_short': 'Mese',
      'timeframe_year_short': 'Anno',
      'timeframe_all': 'Tutto',
      'week': 'Sett',
      'month': 'Mese',
      'year': 'Anno',
      'all': 'Tutto',
      '7d': '7g',
      '14d': '14g',
      '30d': '30g',
      'Trend Completamento': 'Trend Completamento',
      'Performance Evolution': 'Evoluzione Performance',
      'Sett': 'Sett',
      'Tutto': 'Tutto',
      'Confronto Temporale': 'Confronto Temporale',
      'Analizza come stai andando rispetto al passato.': 'Analizza come stai andando rispetto al passato.',
      'vs': 'vs',
      'Aree di Miglioramento': 'Aree di Miglioramento',
      'Abitudini che richiedono più attenzione.': 'Abitudini che richiedono più attenzione.',
      'succ.': 'succ.',
      'GIORNO NERO': 'GIORNO NERO',
      'Solo il': 'Solo il',
      'di completamento': 'di completamento',
      'Analisi Worst Streaks': 'Analisi Worst Streaks',
      'Analisi serie negative per identificare pattern.': 'Analisi serie negative per identificare pattern.',
      'Abitudini Critiche': 'Abitudini Critiche',
      'Top 3 Worst Streaks': 'Top 3 Worst Streaks',
      'giorni consecutivi': 'giorni consecutivi',
      'Analisi Fallimenti': 'Analisi Fallimenti',
      'Pattern di Recupero': 'Pattern di Recupero',
      'Tempo Medio Recupero': 'Tempo Medio Recupero',
      'Buono': 'Buono',
      'RECUPERATORI VELOCI': 'RECUPERATORI VELOCI',
      'Confronto Performance': 'Confronto Performance',
      'Attenzione': 'Attenzione',
      'Suggerimenti Pratici': 'Suggerimenti Pratici',
      'Dettagli Abitudini': 'Dettagli Abitudini',
      'Ordina per': 'Ordina per',
      'Rate': 'Rate',
      'Peggior Serie': 'Peggior Serie',
      'Serie Attuale': 'Serie Attuale',
      'ORDINA PER': 'ORDINA PER',
      'Mood & Energy vs Productivity': 'Mood & Energy vs Productivity',
      'Correlazione tra benessere e abitudini': 'Correlazione tra benessere e abitudini',
      'time_range_7d': '7gg',
      'time_range_14d': '14gg',
      'time_range_30d': '30gg',
      'Produttività': 'Produttività',
      'Sensibili al Mood': 'Sensibili al Mood',
      'Richiedono un buon mood per essere completate.': 'Richiedono un buon mood per essere completate.',
      'con mood basso': 'con mood basso',
      'con mood alto': 'con mood alto',
      'Resilienti': 'Resilienti',
      'Mantenute anche con mood ed energia bassi.': 'Mantenute anche con mood ed energia bassi.',
      'Mood': 'Mood',
      'Stabile': 'Stabile',
      'Suggerimenti': 'Suggerimenti',
      'Pianifica le abitudini sensibili al mood quando ti senti meglio.': 'Pianifica le abitudini sensibili al mood quando ti senti meglio.',
      'Le abitudini resilienti sono ottime nei giorni difficili.': 'Le abitudini resilienti sono ottime nei giorni difficili.',
      'Monitora mood ed energia per insights più accurati.': 'Monitora mood ed energia per insights più accurati.',
      'SERIE ATTUALE': 'SERIE ATTUALE',
      'RECORD': 'RECORD',
      'COMPLETAMENTO': 'COMPLETAMENTO',
      'MANCATI': 'MANCATI',
      'Trend Ultimi 30 Giorni': 'Trend Ultimi 30 Giorni',
      'Completato': 'Completato',
      'Non completato': 'Non completato',
      'Correlazioni con': 'Correlazioni con',
      'Come questa abitudine si relaziona con le altre': 'Come questa abitudine si relaziona con le altre',
      'insieme': 'insieme',
      'Info Correlazioni': 'Le correlazioni positive suggeriscono abitudini che funzionano bene insieme. Le negative indicano possibili conflitti di tempo o energia.',
      'Calendario Annuale': 'Calendario Annuale',
      'Mancato': 'Mancato',
      'Non tracciato': 'Non tracciato',
      'Performance per Giorno': 'Performance per Giorno',
      'Giorno più forte': 'Giorno più forte',
      'Giorno più debole': 'Giorno più debole',
      'Ben fatto! % di completamento': 'Ben fatto! % di completamento',
      'Solo % di completamento': 'Solo % di completamento',
      'Serie Negativa Peggiore': 'Serie Negativa Peggiore',
      'giorni consecutivi mancati': 'giorni consecutivi mancati',
      'Iniziata il': 'Iniziata il',
      'Streak Interrotti': 'Streak Interrotti',
      'Streak di count giorni interrotto': 'Streak di count giorni interrotto',
      'Concentrati sul Dom - è il tuo giorno più debole': 'Concentrati sul Dom - è il tuo giorno più debole',
      'Evita pause prolungate - la tua serie negativa più lunga è stata di 12 giorni': 'Evita pause prolungate - la tua serie negativa più lunga è stata di 12 giorni',
      'Obiettivo: raggiungi almeno il 70% di completamento per consolidare l\'abitudine': 'Obiettivo: raggiungi almeno il 70% di completamento per consolidare l\'abitudine',
      'Traccia il tuo umore ed energia.': 'Traccia il tuo umore ed energia.',
      'Scegli un colore': 'Scegli un colore',
      'Es. Bere acqua, Leggere...': 'Es. Bere acqua, Leggere...',
      'Correlazione Mood': 'Correlazione Mood',
      'Correlazione Energia': 'Correlazione Energia',
      'Mood Medio (✓)': 'Mood Medio (✓)',
      'Energia Media (✓)': 'Energia Media (✓)',
      'Nessuna': 'Nessuna',
      'su 10': 'su 10',
      'Resiliente': 'Resiliente',
      'Completato vs Mancato': 'Completato vs Mancato',
      'Performance per Livello': 'Performance per Livello',
      'Basso (1-4) • Medio (5-7) • Alto (8-10)': 'Basso (1-4) • Medio (5-7) • Alto (8-10)',
      'Basso': 'Basso',
      'Medio': 'Medio',
      'Alto': 'Alto',
      'Con Mood': 'Con Mood',
      'Con Energia': 'Con Energia',
      'Analisi basata su count giorni con dati mood/energia (done completati, missed mancati)': 'Analisi basata su count giorni con dati mood/energia (done completati, missed mancati)',
      'Nome': 'Nome',
      'Cognome': 'Cognome',
      'Email': 'Email',
      'Telefono (Opzionale)': 'Telefono (Opzionale)',
      'Informazioni salvate con successo': 'Informazioni salvate con successo',
      'Campo obbligatorio': 'Campo obbligatorio',
      'Inserisci un\'email valida': 'Inserisci un\'email valida',
      'Giorno': 'Giorno',
      'Buongiorno': 'Buongiorno',
      'Buon pomeriggio': 'Buon pomeriggio',
      'Buonasera': 'Buonasera',
      'Bentornato': 'Bentornato',
      'Sistema Sincronizzato': 'Sistema Sincronizzato',
      'succ': 'succ.',
      'only': 'Solo',
      'attention': 'Attenzione',
      'monday': 'Lunedì',
      'tuesday': 'Martedì',
      'wednesday': 'Mercoledì',
      'thursday': 'Giovedì',
      'friday': 'Venerdì',
      'saturday': 'Sabato',
      'sunday': 'Domenica',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Gio',
      'fri': 'Ven',
      'sat': 'Sab',
      'sun': 'Dom',
      'january': 'Gennaio',
      'february': 'Febbraio',
      'march': 'Marzo',
      'april': 'Aprile',
      'may': 'Maggio',
      'june': 'Giugno',
      'july': 'Luglio',
      'august': 'Agosto',
      'september': 'Settembre',
      'october': 'Ottobre',
      'november': 'Novembre',
      'december': 'Dicembre',
      'rate': 'Tasso di Successo',
      'best_streak_label': 'Miglior Serie',
      'worst_streak_label': 'Peggior Serie',
      'current_streak_label': 'Serie Attuale',
      'first_name': 'Nome',
      'Crea Abitudine': 'Crea Abitudine',
      'Puoi modificare solo oggi e ieri!': 'Puoi modificare solo oggi e ieri!',
      'Nessun dato': 'Nessun dato',
      'Dati insufficienti (servono almeno 3 categorie)': 'Dati insufficienti (servono almeno 3 categorie)',
      'Distribuzione': 'Distribuzione',
      'obiettivi': 'obiettivi',
      'nascita': 'nascita',
      '85 anni': '85 anni',
      'Sensibilità': 'Sensibilità',
      'Streak Negativa': 'Streak Negativa',
      'Coming Soon': 'Coming Soon',
      'Errore': 'Errore',
      'Impossibile aprire il link.': 'Impossibile aprire il link.',
      'Colore Personalizzato': 'Colore Personalizzato',
      'Verifica': 'Verifica',
      'Problemi di connessione con il Coach. Riprova più tardi.': 'Problemi di connessione con il Coach. Riprova più tardi.',
      'AI Coach': 'AI Coach',
      'Password aggiornata con successo!': 'Password aggiornata con successo!',
      'Errore durante l\'esportazione: ': 'Errore durante l\'esportazione: ',
      'Dati resettati con successo!': 'Dati resettati con successo!',
      'Errore durante il reset: ': 'Errore durante il reset: ',
      'Account eliminato con successo!': 'Account eliminato con successo!',
      'Errore durante l\'eliminazione: ': 'Errore durante l\'eliminazione: ',
      'Ripristina acquisti': 'Ripristina acquisti',
      'Errore durante il salvataggio.': 'Errore durante il salvataggio.',
      'Fatto': 'Fatto',
      'Inserisci la tua email per reimpostare la password.': 'Inserisci la tua email per reimpostare la password.',
      'Tasso di successo': 'Tasso di successo',
      'Tasso di successo per categoria': 'Tasso di successo per categoria',
      'Attività Trim.': 'Attività Trim.',
      'Q1 - Q4': 'Q1 - Q4',
      'In Q1-Q4': 'In Q1-Q4',
      'Attività Mensile': 'Attività Mensile',
      'Totale/Completati': 'Totale/Completati',
      'Completamenti': 'Completamenti',
      'Mensili': 'Mensili',
      'Totali: ': 'Totali: ',
      'Completati: ': 'Completati: ',
      '🎯 Distribuzione Categorie': '🎯 Distribuzione Categorie',
      'Ripartizione degli obiettivi per area di focus': 'Ripartizione degli obiettivi per area di focus',
      '📈 Progressione Annuale': '📈 Progressione Annuale',
      'Confronto anno per anno del volume di obiettivi e completamenti': 'Confronto anno per anno del volume di obiettivi e completamenti',
      'Attivi: ': 'Attivi: ',
      'Falliti: ': 'Falliti: ',
      '🔮 Distribuzione Tipologie': '🔮 Distribuzione Tipologie',
      'Ripartizione degli obiettivi per orizzonte temporale': 'Ripartizione degli obiettivi per orizzonte temporale',
      '🎂 Stagionalità': '🎂 Stagionalità',
      'Performance Trimestrale aggregata': 'Performance Trimestrale aggregata',
      '📈 Mensile (Storico)': '📈 Mensile (Storico)',
      'Successo medio per mese': 'Successo medio per mese',
      ' successo': ' successo',
      '📈 Evoluzione Interessi': '📈 Evoluzione Interessi',
      'Composizione delle aree di focus negli anni': 'Composizione delle aree di focus negli anni',
      'Modifica categoria': 'Modifica categoria',
      'Archivia categoria': 'Archivia categoria',
      'Nome categoria...': 'Nome categoria...',
      'Titolo obiettivo...': 'Titolo obiettivo...',
      'Cambia categoria': 'Cambia categoria',
      'Scegli categoria': 'Scegli categoria',
      'Punto di Forza': 'Punto di Forza',
      'Mese Migliore': 'Mese Migliore',
      'Nessuno': 'Nessuno',
      'Tipologia Efficace': 'Tipologia Efficace',
      'Totale Storico': 'Totale Storico',
      'dal ': 'dal ',
      'Successo Globale': 'Successo Globale',
      'obiettivi completati': 'obiettivi completati',
      'Anno Migliore': 'Anno Migliore',
      'Anno Più Produttivo': 'Anno Più Produttivo',
      'obiettivi totali': 'obiettivi totali',
      '🚀 Velocità di Esecuzione (Cumulativa)': '🚀 Velocità di Esecuzione (Cumulativa)',
      'Confronto tra obiettivi pianificati e completati nel tempo': 'Confronto tra obiettivi pianificati e completati nel tempo',
      '🎯 Performance Categorie': '🎯 Performance Categorie',
      'Tutto alla grande!': 'Tutto alla grande!',
      'WORST STREAK': 'WORST STREAK',
      'FREQUENZA': 'FREQUENZA',
      'BEST': 'BEST',
      'WORST': 'WORST',
      'Gap: ': 'Gap: ',
      'MOOD ALTO': 'MOOD ALTO',
      'Coefficiente': 'Coefficiente',
      'Co-occorrenza': 'Co-occorrenza',
      'Errore durante la creazione della categoria': 'Errore durante la creazione della categoria',
      'Errore durante la modifica della categoria': 'Errore durante la modifica della categoria',
      'Errore durante l\'archiviazione della categoria': 'Errore durante l\'archiviazione della categoria',
      'Errore durante l\'aggiornamento': 'Errore durante l\'aggiornamento',
      'Errore durante l\'aggiornamento dello stato': 'Errore durante l\'aggiornamento dello stato',
      'Errore durante il salvataggio dell\'umore': 'Errore durante il salvataggio dell\'umore',
      'Lavoro': 'Lavoro',
      'Salute': 'Salute',
      'Finanza': 'Finanza',
      'Relazioni': 'Relazioni',
      'Formazione': 'Formazione',
      'Hobby': 'Hobby',
      'Spirituale': 'Spirituale',
      'Altro': 'Altro',
      'Evolve • ': 'Evolve • ',
      'Errore durante il salvataggio': 'Errore durante il salvataggio',
      'Errore durante l\'eliminazione': 'Errore durante l\'eliminazione',

      'App Bloccata': 'App Bloccata',
      'Sblocca con i dati biometrici per continuare': 'Sblocca con i dati biometrici per continuare',
      'Riprova': 'Riprova',
      'La tua tela è vuota': 'La tua tela è vuota',
      'Crea la tua prima abitudine per iniziare a tracciare i tuoi progressi e costruire la tua routine.': 'Crea la tua prima abitudine per iniziare a tracciare i tuoi progressi e costruire la tua routine.',
    },
    'English': {
      'app_title': 'Evolve',
      'Impostazioni App': 'App Settings',
      'ASPETTO & VISUAL': 'APPEARANCE & VISUAL',
      'Modalità Scura': 'Dark Mode',
      'Colore Accento': 'Accent Color',
      'CALENDARIO & DASHBOARD': 'CALENDARIO & DASHBOARD',
      'Vista Predefinita': 'Default View',
      'ESPERIENZA UTENTE': 'USER EXPERIENCE',
      'Feedback Aptico': 'Haptic Feedback',
      'UNITÀ E LINGUA': 'UNITS & LANGUAGE',
      'Lingua': 'Language',
      'Formato 24h': '24h Format',
      'AI & SISTEMA': 'AI & SYSTEM',
      'Suggerimenti AI': 'AI Suggestions',
      'Analisi intelligente delle abitudini': 'Intelligent habit analysis',
      'PRO ONLY': 'This feature is only available for PRO users',
      'Home': 'Home',
      'Statistiche': 'Statistics',
      'Obiettivi': 'Goals',
      'Salva': 'Save',
      'Annulla': 'Cancel',
      'Conferma': 'Confirm',
      'Aggiorna Stato Giornaliero': 'Update Daily Status',
      'Check-in Giornaliero': 'Daily Check-in',
      'Oggi': 'Today',
      'Abitudini': 'Habits',
      'Umore': 'Mood',
      'Energia': 'Energy',
      'AI Chat': 'AI Chat',
      'Morning Brief': 'Morning Brief',
      'Review Serale': 'Evening Review',
      'Notifiche': 'Notifications',
      'Privacy e Sicurezza': 'Privacy & Security',
      'Account': 'Account',
      'Piano PRO': 'PRO Plan',
      'Informazioni Personali': 'Personal Information',
      'Blocco Biometrico': 'Biometric Lock',
      'Analytics Anonimi': 'Anonymous Analytics',
      'Promemoria Abitudini': 'Habit Reminders',
      'Scadenze Obiettivi': 'Goal Deadlines',
      'Insight AI': 'AI Insights',
      'Resoconti Settimanali': 'Weekly Reports',
      'Modalità Focus': 'Focus Mode',
      'Milestones': 'Milestones',
      'Deep Work Insights': 'Deep Work Insights',
      'Gestione Abitudini': 'Manage Habits',
      'Aggiungi Abitudine': 'Add Habit',
      'Modifica Abitudine': 'Edit Habit',
      'Elimina Abitudine': 'Delete Habit',
      'Nome Abitudine': 'Habit Name',
      'Colore': 'Color',
      'Trascina per riordinare': 'Drag to reorder',
      'Nessuna abitudine tracciata oggi': 'No habits tracked today',
      'Panoramica Statistiche': 'Statistics Overview',
      'Mese': 'Month',
      'Settimana': 'Week',
      'Anno': 'Year',
      'Vita': 'Life',
      'Analisi dettagliata delle tue performance.': 'Detailed analysis of your performance.',
      'Tutti gli Habits': 'All Habits',
      'SELEZIONA HABIT': 'SELECT HABIT',
      'Info': 'Info',
      'Trend': 'Trend',
      'Alert': 'Alert',
      'Stats': 'Stats',
      'Completamento': 'Completion',
      'Globale': 'Global',
      'Miglior Serie': 'Best Streak',
      'Giorni': 'Days',
      'Top Performer': 'Top Performer',
      'Giorno Critico': 'Critical Day',
      'Focus richiesto': 'Focus Required',
      'Abitudini Chiave': 'Key Habits',
      'Abitudini che influenzano positivamente molte altre': 'Habits that positively influence many others',
      'Alto Impatto': 'High Impact',
      'connessioni': 'connections',
      'Media Impatto': 'Avg Impact',
      'Analisi Correlazioni': 'Correlation Analysis',
      'Pattern tra le tue abitudini': 'Patterns between your habits',
      'Coppie Analizzate': 'Pairs Analyzed',
      'Correlazione Media': 'Avg Correlation',
      'Positive': 'Positive',
      'Negative': 'Negative',
      'Abitudini Isolate': 'Isolated Habits',
      'Non hanno correlazioni significative.': 'No significant correlations found.',
      'Correlazioni Positive': 'Positive Correlations',
      'Correlazioni Negative': 'Negative Correlations',
      'Attività Recente': 'Recent Activity',
      'Suggerimento': 'Suggestion',
      'Le abitudini chiave have un effetto "domino".': 'Key habits have a "domino" effect.',
      'timeframe_week_short': 'Week',
      'timeframe_month_short': 'Month',
      'timeframe_year_short': 'Year',
      'timeframe_all': 'All',
      'week': 'Week',
      'month': 'Month',
      'year': 'Year',
      'all': 'All',
      '7d': '7d',
      '14d': '14d',
      '30d': '30d',
      'Trend Completamento': 'Completion Trend',
      'Performance Evolution': 'Performance Evolution',
      'Sett': 'Week',
      'Tutto': 'All',
      'Confronto Temporale': 'Temporal Comparison',
      'Analizza come stai andando rispetto al passato.': 'Analyze how you are doing compared to the past.',
      'vs': 'vs',
      'Aree di Miglioramento': 'Improvement Areas',
      'Abitudini che richiedono più attenzione.': 'Habits requiring more attention.',
      'succ.': 'succ.',
      'GIORNO NERO': 'BLACK DAY',
      'Solo il': 'Only',
      'di completamento': 'of completion',
      'Analisi Worst Streaks': 'Worst Streaks Analysis',
      'Analisi serie negative per identificare pattern.': 'Analyzing negative streaks to find patterns.',
      'Abitudini Critiche': 'Critical Habits',
      'Top 3 Worst Streaks': 'Top 3 Worst Streaks',
      'giorni consecutivi': 'consecutive days',
      'Analisi Fallimenti': 'Failure Analysis',
      'Pattern di Recupero': 'Recovery Patterns',
      'Tempo Medio Recupero': 'Avg Recovery Time',
      'Buono': 'Good',
      'RECUPERATORI VELOCI': 'FAST RECOVERERS',
      'Confronto Performance': 'Performance Comparison',
      'Attenzione': 'Attention',
      'Suggerimenti Pratici': 'Practical Suggestions',
      'Dettagli Abitudini': 'Habit Details',
      'Ordina per': 'Sort by',
      'Rate': 'Rate',
      'Peggior Serie': 'Worst Streak',
      'Serie Attuale': 'Current Streak',
      'ORDINA PER': 'ORDER BY',
      'Mood & Energy vs Productivity': 'Mood & Energy vs Productivity',
      'Correlazione tra benessere e abitudini': 'Wellbeing & habit correlation',
      'time_range_7d': '7d',
      'time_range_14d': '14d',
      'time_range_30d': '30d',
      'Produttività': 'Productivity',
      'Sensibili al Mood': 'Mood Sensitive',
      'Richiedono un buon mood per essere completate.': 'These habits require a good mood to be completed.',
      'con mood basso': 'with low mood',
      'con mood alto': 'with high mood',
      'Resilienti': 'Resilient',
      'Mantenute anche con mood ed energia bassi.': 'Maintained even when mood and energy are low.',
      'Mood': 'Mood',
      'Stabile': 'Stable',
      'Suggerimenti': 'Suggestions',
      'Pianifica le abitudini sensibili al mood quando ti senti meglio.': 'Plan mood-sensitive habits when you feel best.',
      'Le abitudini resilienti sono ottime nei giorni difficili.': 'Resilient habits are great to keep on difficult days.',
      'Monitora mood ed energia for insights più accurati.': 'Track mood and energy for more accurate insights.',
      'SERIE ATTUALE': 'CURRENT STREAK',
      'RECORD': 'RECORD',
      'COMPLETAMENTO': 'COMPLETATION',
      'MANCATI': 'MISSED',
      'Trend Ultimi 30 Giorni': 'Last 30 Days Trend',
      'Completato': 'Completed',
      'Non completato': 'Not completed',
      'Correlazioni con': 'Correlations with',
      'Come questa abitudine si relaziona con le altre': 'How this habit relates to others',
      'insieme': 'together',
      'Info Correlazioni': 'Positive correlations suggest habits that work well together. Negative ones indicate possible conflicts of time or energy.',
      'Calendario Annuale': 'Annual Calendar',
      'Mancato': 'Missed',
      'Non tracciato': 'Not tracked',
      'Performance per Giorno': 'Performance per Day',
      'Giorno più forte': 'Strongest day',
      'Giorno più debole': 'Weakest day',
      'Ben fatto! % di completamento': 'Well done! % completion',
      'Solo % di completamento': 'Only % completion',
      'Serie Negativa Peggiore': 'Worst Negative Streak',
      'giorni consecutivi mancati': 'missed consecutive days',
      'Iniziata il': 'Started on',
      'Streak Interrotti': 'Broken Streaks',
      'Streak di count giorni interrotto': 'Streak of count days broken',
      'Concentrati sul Dom - è il tuo giorno più debole': 'Focus on Sun - it\'s your weakest day',
      'Evita pause prolungate - la tua serie negativa più lunga è stata di 12 giorni': 'Avoid prolonged breaks - your longest negative streak was 12 days',
      'Obiettivo: raggiungi almeno il 70% di completamento per consolidare l\'abitudine': 'Goal: reach at least 70% completion to consolidate the habit',
      'Traccia il tuo umore ed energia.': 'Track your mood and energy.',
      'Scegli un colore': 'Choose a color',
      'Es. Bere acqua, Leggere...': 'e.g. Drink water, Read...',
      'Correlazione Mood': 'Mood Correlation',
      'Correlazione Energia': 'Energy Correlation',
      'Mood Medio (✓)': 'Avg Mood (✓)',
      'Energia Media (✓)': 'Avg Energy (✓)',
      'Nessuna': 'None',
      'su 10': 'of 10',
      'Resiliente': 'Resilient',
      'Completato vs Mancato': 'Completed vs Missed',
      'Performance per Livello': 'Performance per Level',
      'Basso (1-4) • Medio (5-7) • Alto (8-10)': 'Low (1-4) • Medium (5-7) • High (8-10)',
      'Basso': 'Low',
      'Medio': 'Medium',
      'Alto': 'High',
      'Con Mood': 'With Mood',
      'Con Energia': 'With Energy',
      'Analisi basata su count giorni con dati mood/energia (done completati, missed mancati)': 'Analysis based on count days with mood/energy data (done completed, missed missed)',
      'Nome': 'First Name',
      'Cognome': 'Last Name',
      'Email': 'Email',
      'Telefono (Opzionale)': 'Phone (Optional)',
      'Informazioni salvate con successo': 'Information saved successfully',
      'Campo obbligatorio': 'Required field',
      'Inserisci un\'email valida': 'Enter a valid email',
      'Giorno': 'Day',
      'Buongiorno': 'Good morning',
      'Buon pomeriggio': 'Good afternoon',
      'Buonasera': 'Good evening',
      'Bentornato': 'Welcome back',
      'Sistema Sincronizzato': 'System Synced',
      'succ': 'succ.',
      'only': 'Only',
      'attention': 'Attention',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
      'rate': 'Success Rate',
      'best_streak_label': 'Best Streak',
      'worst_streak_label': 'Worst Streak',
      'current_streak_label': 'Current Streak',
      'first_name': 'Name',
      'Crea Abitudine': 'Create Habit',
      'Puoi modificare solo oggi e ieri!': 'You can only edit today and yesterday!',
      'Nessun dato': 'No data',
      'Dati insufficienti (servono almeno 3 categorie)': 'Insufficient data (at least 3 categories needed)',
      'Distribuzione': 'Distribution',
      'obiettivi': 'goals',
      'nascita': 'birth',
      '85 anni': '85 years',
      'Sensibilità': 'Sensitivity',
      'Streak Negativa': 'Negative Streak',
      'Coming Soon': 'Coming Soon',
      'Errore': 'Error',
      'Impossibile aprire il link.': 'Unable to open the link.',
      'Colore Personalizzato': 'Custom Color',
      'Verifica': 'Verify',
      'Problemi di connessione con il Coach. Riprova più tardi.': 'Connection issues with the Coach. Try again later.',
      'AI Coach': 'AI Coach',
      'Password aggiornata con successo!': 'Password updated successfully!',
      'Errore durante l\'esportazione: ': 'Error during export: ',
      'Dati resettati con successo!': 'Data reset successfully!',
      'Errore durante il reset: ': 'Error during reset: ',
      'Account eliminato con successo!': 'Account deleted successfully!',
      'Errore durante l\'eliminazione: ': 'Error during deletion: ',
      'Ripristina acquisti': 'Restore purchases',
      'Errore durante il salvataggio.': 'Error during saving.',
      'Fatto': 'Done',
      'Inserisci la tua email per reimpostare la password.': 'Enter your email to reset the password.',
      'Tasso di successo': 'Success rate',
      'Tasso di successo per categoria': 'Success rate by category',
      'Attività Trim.': 'Quarterly Activity',
      'Q1 - Q4': 'Q1 - Q4',
      'In Q1-Q4': 'In Q1-Q4',
      'Attività Mensile': 'Monthly Activity',
      'Totale/Completati': 'Total/Completed',
      'Completamenti': 'Completions',
      'Mensili': 'Monthly',
      'Totali: ': 'Total: ',
      'Completati: ': 'Completed: ',
      '🎯 Distribuzione Categorie': '🎯 Category Distribution',
      'Ripartizione degli obiettivi per area di focus': 'Breakdown of goals by focus area',
      '📈 Progressione Annuale': '📈 Annual Progression',
      'Confronto anno per anno del volume di obiettivi e completamenti': 'Year-over-year comparison of goals volume and completions',
      'Attivi: ': 'Active: ',
      'Falliti: ': 'Failed: ',
      '🔮 Distribuzione Tipologie': '🔮 Type Distribution',
      'Ripartizione degli obiettivi per orizzonte temporale': 'Breakdown of goals by time horizon',
      '🎂 Stagionalità': '🎂 Seasonality',
      'Performance Trimestrale aggregata': 'Aggregated Quarterly Performance',
      '📈 Mensile (Storico)': '📈 Monthly (Historical)',
      'Successo medio per mese': 'Average success per month',
      ' successo': ' success',
      '📈 Evoluzione Interessi': '📈 Interest Evolution',
      'Composizione delle aree di focus negli anni': 'Composition of focus areas over the years',
      'Modifica categoria': 'Edit category',
      'Archivia categoria': 'Archive category',
      'Nome categoria...': 'Category name...',
      'Titolo obiettivo...': 'Goal title...',
      'Cambia categoria': 'Change category',
      'Scegli categoria': 'Choose category',
      'Punto di Forza': 'Strength',
      'Mese Migliore': 'Best Month',
      'Nessuno': 'None',
      'Tipologia Efficace': 'Effective Type',
      'Totale Storico': 'Historical Total',
      'dal ': 'since ',
      'Successo Globale': 'Global Success',
      'obiettivi completati': 'completed goals',
      'Anno Migliore': 'Best Year',
      'Anno Più Produttivo': 'Most Productive Year',
      'obiettivi totali': 'total goals',
      '🚀 Velocità di Esecuzione (Cumulativa)': '🚀 Execution Speed (Cumulative)',
      'Confronto tra obiettivi pianificati e completati nel tempo': 'Comparison of planned vs completed goals over time',
      '🎯 Performance Categorie': '🎯 Category Performance',
      'Tutto alla grande!': 'Everything is great!',
      'WORST STREAK': 'WORST STREAK',
      'FREQUENZA': 'FREQUENCY',
      'BEST': 'BEST',
      'WORST': 'WORST',
      'Gap: ': 'Gap: ',
      'MOOD ALTO': 'HIGH MOOD',
      'Coefficiente': 'Coefficient',
      'Co-occorrenza': 'Co-occurrence',
      'Errore durante la creazione della categoria': 'Error creating category',
      'Errore durante la modifica della categoria': 'Error editing category',
      'Errore durante l\'archiviazione della categoria': 'Error archiving category',
      'Errore durante l\'aggiornamento': 'Error during update',
      'Errore durante l\'aggiornamento dello stato': 'Error updating state',
      'Errore durante il salvataggio dell\'umore': 'Error saving mood',
      'Lavoro': 'Work',
      'Salute': 'Health',
      'Finanza': 'Finance',
      'Relazioni': 'Relationships',
      'Formazione': 'Education',
      'Hobby': 'Hobbies',
      'Spirituale': 'Spiritual',
      'Altro': 'Other',
      'Evolve • ': 'Evolve • ',
      'Errore durante il salvataggio': 'Error during saving',
      'Errore durante l\'eliminazione': 'Error during deletion',

      'App Bloccata': 'App Locked',
      'Sblocca con i dati biometrici per continuare': 'Unlock with biometrics to continue',
      'Riprova': 'Retry',
      'La tua tela è vuota': 'Your canvas is empty',
      'Crea la tua prima abitudine per iniziare a tracciare i tuoi progressi e costruire la tua routine.': 'Create your first habit to start tracking your progress and build your routine.',

      // Auth Screen
      'Crea il tuo ecosistema personale.': 'Create your personal ecosystem.',
      'Inserisci la tua email.': 'Please enter your email.',
      'Email non valida.': 'Invalid email.',
      'Inserisci la password.': 'Please enter your password.',
      'Minimo 6 caratteri.': 'Minimum 6 characters.',
      'Password dimenticata?': 'Forgot password?',
      'OPPURE': 'OR',
      'Continua con Apple': 'Continue with Apple',
      'Continua con Google': 'Continue with Google',
      'Non hai un account?': 'Don\'t have an account?',
      'Hai già un account?': 'Already have an account?',
      'Registrati': 'Sign Up',
      'Accedi': 'Log In',
      'Crea Account': 'Create Account',
      'Termini di Servizio': 'Terms of Service',
      'Password': 'Password',

      // Onboarding & Welcome
      'Daily Check-in': 'Daily Check-in',
      'Qui puoi registrare il tuo stato d\'animo quotidiano per tracciare il tuo benessere nel tempo e soprattutto correlarlo con il completamento dei tuoi obiettivi.': 'Here you can record your daily mood to track your well-being over time and correlate it with the completion of your goals.',
      'Il tuo assistente personale. Chiedi consigli sulle tue abitudini. Lui è il tuo coach.': 'Your personal AI assistant. Ask for advice about your habits. He is your coach.',
      'Aggiungi, modifica o elimina le tue abitudini quotidiane che vuoi rispettare in modo semplice e veloce.': 'Add, edit or delete daily habits you want to maintain quickly and easily.',
      'Viste Calendario': 'Calendar Views',
      'Naviga tra le diverse visualizzazioni per vedere i tuoi progressi con varie alternative.': 'Navigate between different views to see your progress with various alternatives.',
      'Calendario': 'Calendar',
      'Basta cliccare su un giorno per visualizzare le abitudini giornaliere e spuntarle.': 'Simply click on a day to view daily habits and check them off.',
      'Passiamo agli Obiettivi': 'Moving to Goals',
      'La pagina dove puoi gestire i tuoi obiettivi a lungo termine e relative performance.': 'The page where you can manage your long-term goals and their performance.',
      'Vai agli Obiettivi': 'Go to Goals',
      'Inizia il Tour': 'Start Tour',
      'Sei pronto!': 'You are ready!',
      'Il viaggio inizia ora. Dai il massimo!': 'The journey starts now. Give your best!',
      'Inizia': 'Start',
      'Benvenuto in Evolve!': 'Welcome to Evolve!',
      'Per iniziare, come possiamo chiamarti?': 'To start, what should we call you?',
      'Il tuo nome': 'Your name',
      'Inizia ora': 'Start now',
      'Errore durante il salvataggio. Riprova.': 'Error saving. Please try again.',
      'Benvenuto in Evolve': 'Welcome to Evolve',
      'Potrebbe essere uno STEP di NON RITORNO... Prima di iniziare però bisogna fare un tour per mostrarti come sfruttare al massimo l\'applicazione.': 'This could be a STEP of NO RETURN... Before starting, let\'s take a quick tour to show you how to get the most out of the application.',

      // Goals Tutorial
      'Tipo di Pianificazione': 'Planning Type',
      'Qui puoi selezionare la visione temporale: Lifetime (per tutta la vita), Annuale, Trimestrale, Mensile o Settimanale.': 'Here you can select the time perspective: Lifetime, Annual, Quarterly, Monthly or Weekly.',
      'Nuovo Obiettivo': 'New Goal',
      'Da qui puoi inserire un nuovo obiettivo. Potrai anche personalizzare le Categorie a tuo piacimento per organizzare tutto al meglio.': 'From here you can insert a new goal. You can also customize Categories to organize everything perfectly.',
      'Completare o Fallire': 'Complete or Fail',
      'Clicca qui per segnare l\'obiettivo come completato. Cliccandolo di nuovo verrà segnato come fallito.': 'Click here to mark the goal as completed. Clicking again will mark it as failed.',
      'Categoria': 'Category',
      'Usa questo pulsante per assegnare rapidamente una categoria all\'obiettivo.': 'Use this button to quickly assign a category to the goal.',
      'Posticipare': 'Reschedule',
      'Se non hai fatto in tempo o i piani sono cambiati, puoi spostare questo obiettivo alla settimana / mese o anno successivo ( in base a dove hai inserito l\'obiettivo).': 'If you ran out of time or plans changed, you can move this goal to the next week / month or year.',
      'Modifica': 'Edit',
      'Se devi semplicemente rinominare l\'obiettivo, usa la matita.': 'If you just need to rename the goal, use the pencil icon.',
      'Elimina': 'Delete',
      'Infine, questo pulsante elimina definitivamente l\'obiettivo.': 'Finally, this button permanently deletes the goal.',
      'Analisi e Statistiche': 'Analysis & Stats',
      'Passa a questa scheda per visualizzare grafici e performance dettagliate selezionando l\'anno corrente o tutti gli anni.': 'Switch to this tab to view charts and detailed performance by selecting the current year or all years.',
      'Continua': 'Continue',
      'Statistiche Abitudini': 'Habit Statistics',
      'Per vedere le statistiche delle tue abitudini giornaliere, puoi spostarti in questa sezione.': 'To view statistics for your daily habits, you can navigate to this section.',
      'Passa alle Statistiche': 'Go to Statistics',
      'Indietro': 'Back',
      'Fine': 'Finish',
      'Avanti': 'Next',
      'Obiettivo Tutorial': 'Tutorial Goal',
      'I miei obiettivi': 'My Goals',

      // Stats Tutorial
      'Filtra per Abitudine': 'Filter by Habit',
      'Da qui puoi selezionare una specifica abitudine per vederne i dettagli, oppure \'Tutti gli Habits\' per una panoramica globale.': 'From here you can select a specific habit to view details, or \'All Habits\' for a global overview.',
      'Sezioni Statistiche': 'Statistics Sections',
      'Naviga tra le varie schede per vedere i Trend, gli Alert sulle performance, l\'andamento delle Abitudini e il tuo Mood.': 'Navigate through the tabs to see Trends, performance Alerts, Habits progress, and your Mood.',
    },
  };

  String translate(String key) {
    final lang = language == 'it' ? 'Italiano' : language == 'en' ? 'English' : language;
    return _localizedValues[lang]?[key] ?? key;
  }
}

final l10nProvider = Provider<AppLocalizations>((ref) {
  final language = ref.watch(settingsProvider.select((s) => s.language));
  return AppLocalizations(language);
});

extension AppLocalizationsExtension on BuildContext {
  AppLocalizations get l10n => ProviderScope.containerOf(this).read(l10nProvider);
}
