import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/settings_provider.dart';

class AppLocalizations {
  final String language;

  AppLocalizations(this.language);

  static final Map<String, Map<String, String>> _localizedValues = {
    'Italiano': {
      'app_title': 'mattioli.OS',
      'settings_title': 'Impostazioni App',
      'appearance_section': 'ASPETTO & VISUAL',
      'dark_mode': 'Modalità Scura',
      'glass_effects': 'Effetti Trasparenza',
      'accent_color': 'Colore Accento',
      'calendar_section': 'CALENDARIO & DASHBOARD',
      'default_view': 'Vista Predefinita',
      'start_monday': 'Inizia di Lunedì',
      'show_weekend': 'Mostra Weekend',
      'user_exp_section': 'ESPERIENZA UTENTE',
      'haptic_feedback': 'Feedback Aptico',
      'units_lang_section': 'UNITÀ E LINGUA',
      'language': 'Lingua',
      'format_24h': 'Formato 24h',
      'ai_system_section': 'AI & SISTEMA',
      'ai_suggestions': 'Suggerimenti AI',
      'ai_subtitle': 'Analisi intelligente delle abitudini',
      'pro_only': 'Questa funzione è disponibile solo per utenti PRO',
      'home': 'Home',
      'statistics': 'Statistiche',
      'goals': 'Obiettivi',
      'save': 'Salva',
      'cancel': 'Annulla',
      'confirm': 'Conferma',
      'update_status': 'Aggiorna Stato Giornaliero',
      'today': 'Oggi',
      'habits': 'Abitudini',
      'mood': 'Umore',
      'energy': 'Energia',
      'notes': 'Note',
      'quick_notes': 'Note Veloci',
      'morning_brief': 'Morning Brief',
      'evening_review': 'Review Serale',
      'notifications_title': 'Notifiche',
      'privacy_title': 'Privacy e Sicurezza',
      'account_title': 'Account',
      'pro_plan': 'Piano PRO',
      'personal_info': 'Informazioni Personali',
      'biometric_lock': 'Blocco Biometrico',
      'analytics': 'Analytics Anonimi',
      'habit_reminders': 'Promemoria Abitudini',
      'goal_deadlines': 'Scadenze Obiettivi',
      'ai_insights': 'Insight AI',
      'weekly_reports': 'Resoconti Settimanali',
      'focus_mode': 'Modalità Focus',
      'milestones': 'Milestones',
      'deep_work': 'Deep Work Insights',
      'manage_habits': 'Gestione Abitudini',
      'add_habit': 'Aggiungi Abitudine',
      'edit_habit': 'Modifica Abitudine',
      'delete_habit': 'Elimina Abitudine',
      'habit_name': 'Nome Abitudine',
      'color': 'Colore',
      'reorder': 'Trascina per riordinare',
      'no_habits': 'Nessuna abitudine tracciata oggi',
      'stats_overview': 'Panoramica Statistiche',
      'month': 'Mese',
      'week': 'Settimana',
      'year': 'Anno',
      'life': 'Vita',
      'statistics_title': 'Statistiche',
      'statistics_subtitle': 'Analisi dettagliata delle tue performance.',
      'all_habits': 'Tutti gli Habits',
      'select_habit': 'SELEZIONA HABIT',
      'tab_info': 'Info',
      'tab_trend': 'Trend',
      'tab_alert': 'Alert',
      'tab_habits': 'Abitudini',
      'tab_mood': 'Mood',
      'tab_stats': 'Stats',
      'completion': 'Completamento',
      'global': 'Globale',
      'best_streak': 'Miglior Serie',
      'days': 'Giorni',
      'top_performer': 'Top Performer',
      'critical_day': 'Giorno Critico',
      'focus_required': 'Focus richiesto',
      'key_habits': 'Abitudini Chiave',
      'key_habits_desc': 'Abitudini che influenzano positivamente molte altre',
      'high_impact': 'Alto Impatto',
      'connections': 'connessioni',
      'avg_impact': 'Media Impatto',
      'correlation_analysis': 'Analisi Correlazioni',
      'patterns_desc': 'Pattern tra le tue abitudini',
      'pairs_analyzed': 'Coppie Analizzate',
      'avg_correlation': 'Correlazione Media',
      'positive': 'Positive',
      'negative': 'Negative',
      'isolated_habits': 'Abitudini Isolate',
      'isolated_habits_desc': 'Non hanno correlazioni significative.',
      'positive_correlations': 'Correlazioni Positive',
      'negative_correlations': 'Correlazioni Negative',
      'recent_activity': 'Attività Recente',
      'suggestion': 'Suggerimento',
      'suggestion_domino': 'Le abitudini chiave hanno un effetto "domino".',
      'completion_trend': 'Trend Completamento',
      'timeframe_week_short': 'Sett',
      'timeframe_month_short': 'Mese',
      'timeframe_year_short': 'Anno',
      'timeframe_all': 'Tutto',
      'temporal_comparison': 'Confronto Temporale',
      'comparison_desc': 'Analizza come stai andando rispetto al passato.',
      'vs': 'vs',
      'improvement_areas': 'Aree di Miglioramento',
      'improvement_areas_desc': 'Abitudini che richiedono più attenzione.',
      'succ': 'succ.',
      'black_day': 'GIORNO NERO',
      'only': 'Solo il',
      'of_completion': 'di completamento',
      'worst_streaks_analysis': 'Analisi Worst Streaks',
      'worst_streaks_desc': 'Analisi serie negative per identificare pattern.',
      'critical_habits': 'Abitudini Critiche',
      'top_3_worst_streaks': 'Top 3 Worst Streaks',
      'consecutive_days': 'giorni consecutivi',
      'failure_analysis': 'Analisi Fallimenti',
      'recovery_patterns': 'Pattern di Recupero',
      'avg_recovery_time': 'Tempo Medio Recupero',
      'good': 'Buono',
      'fast_recoverers': 'RECUPERATORI VELOCI',
      'performance_comparison': 'Confronto Performance',
      'attention': 'Attenzione',
      'practical_suggestions': 'Suggerimenti Pratici',
      'habit_details': 'Dettagli Abitudini',
      'sort_by': 'Ordina per',
      'rate': 'Rate',
      'best_streak_label': 'Miglior Serie',
      'worst_streak_label': 'Peggior Serie',
      'current_streak_label': 'Serie Attuale',
      'order_by': 'ORDINA PER',
      'mood_energy_productivity': 'Mood & Energy vs Productivity',
      'wellbeing_habit_correlation': 'Correlazione tra benessere e abitudini',
      'time_range_7d': '7gg',
      'time_range_14d': '14gg',
      'time_range_30d': '30gg',
      'productivity': 'Produttività',
      'mood_sensitive': 'Sensibili al Mood',
      'mood_sensitive_desc': 'Richiedono un buon mood per essere completate.',
      'with_low_mood': 'con mood basso',
      'with_high_mood': 'con mood alto',
      'resilient': 'Resilienti',
      'resilient_desc': 'Mantenute anche con mood ed energia bassi.',
      'mood_label': 'Mood',
      'energy_label': 'Energia',
      'stable': 'Stabile',
      'suggestions': 'Suggerimenti',
      'mood_tip_1': 'Pianifica le abitudini sensibili al mood quando ti senti meglio.',
      'mood_tip_2': 'Le abitudini resilienti sono ottime nei giorni difficili.',
      'mood_tip_3': 'Monitora mood ed energia per insights più accurati.',
      'current_streak_caps': 'SERIE ATTUALE',
      'record_streak_caps': 'RECORD',
      'completion_caps': 'COMPLETAMENTO',
      'missed_caps': 'MANCATI',
      'trend_last_30_days': 'Trend Ultimi 30 Giorni',
      'completed': 'Completato',
      'not_completed': 'Non completato',
      'correlations_with': 'Correlazioni con',
      'how_habit_relates': 'Come questa abitudine si relaziona con le altre',
      'together': 'insieme',
      'correlation_info': 'Le correlazioni positive suggeriscono abitudini che funzionano bene insieme. Le negative indicano possibili conflitti di tempo o energia.',
      'annual_calendar': 'Calendario Annuale',
      'missed': 'Mancato',
      'not_tracked': 'Non tracciato',
      'performance_per_day': 'Performance per Giorno',
      'strongest_day_label': 'Giorno più forte',
      'weakest_day_label': 'Giorno più debole',
      'well_done_completion': 'Ben done% di completamento',
      'only_completion': 'Solo done% di completamento',
      'worst_negative_streak': 'Serie Negativa Peggiore',
      'missed_consecutive_days': 'giorni consecutivi mancati',
      'started_on': 'Iniziata il',
      'broken_streaks': 'Streak Interrotti',
      'streak_of_days_broken': 'Streak di count giorni interrotto',
      'improvement_tip_1': 'Concentrati sul Dom - è il tuo giorno più debole',
      'improvement_tip_2': 'Evita pause prolungate - la tua serie negativa più lunga è stata di 12 giorni',
      'improvement_tip_3': 'Obiettivo: raggiungi almeno il 70% di completamento per consolidare l\'abitudine',
      'track_mood_energy': 'Traccia il tuo umore ed energia.',
      'choose_color': 'Scegli un colore',
      'habit_hint': 'Es. Bere acqua, Leggere...',
      'mood_correlation': 'Correlazione Mood',
      'energy_correlation': 'Correlazione Energia',
      'avg_mood_checked': 'Mood Medio (✓)',
      'avg_energy_checked': 'Energia Media (✓)',
      'none': 'Nessuna',
      'on_10': 'su 10',
      'resilient_label': 'Resiliente',
      'completed_vs_missed': 'Completato vs Mancato',
      'performance_per_level': 'Performance per Livello',
      'low_med_high_desc': 'Basso (1-4) • Medio (5-7) • Alto (8-10)',
      'low': 'Basso',
      'medium': 'Medio',
      'high': 'Alto',
      'with_mood': 'Con Mood',
      'with_energy': 'Con Energia',
      'analysis_based_on': 'Analisi basata su count giorni con dati mood/energia (done completati, missed mancati)',
      'first_name': 'Nome',
      'last_name': 'Cognome',
      'email': 'Email',
      'phone_optional': 'Telefono (Opzionale)',
      'success_save': 'Informazioni salvate con successo',
      'error_required': 'Campo obbligatorio',
      'error_email': 'Inserisci un\'email valida',
      'mon': 'Lun',
      'tue': 'Mar',
      'wed': 'Mer',
      'thu': 'Gio',
      'fri': 'Ven',
      'sat': 'Sab',
      'sun': 'Dom',
      'monday': 'Lunedì',
      'tuesday': 'Martedì',
      'wednesday': 'Mercoledì',
      'thursday': 'Giovedì',
      'friday': 'Venerdì',
      'saturday': 'Sabato',
      'sunday': 'Domenica',
      'january': 'Gennaio',
      'february': 'Febbraio',
      'march': 'Marzo',
      'april': 'Aprile',
      'may': 'Maggio',
      'june': 'Giugno',
      'july': 'Luglio',
      'august': 'Agosto',
      'september': 'Settembre',
      'october': 'Ottobre',
      'november': 'Novembre',
      'december': 'Dicembre',
    },
    'English': {
      'app_title': 'mattioli.OS',
      'settings_title': 'App Settings',
      'appearance_section': 'APPEARANCE & VISUAL',
      'dark_mode': 'Dark Mode',
      'glass_effects': 'Glass Effects',
      'accent_color': 'Accent Color',
      'calendar_section': 'CALENDAR & DASHBOARD',
      'default_view': 'Default View',
      'start_monday': 'Start on Monday',
      'show_weekend': 'Show Weekend',
      'user_exp_section': 'USER EXPERIENCE',
      'haptic_feedback': 'Haptic Feedback',
      'units_lang_section': 'UNITS & LANGUAGE',
      'language': 'Language',
      'format_24h': '24h Format',
      'ai_system_section': 'AI & SYSTEM',
      'ai_suggestions': 'AI Suggestions',
      'ai_subtitle': 'Intelligent habit analysis',
      'pro_only': 'This feature is only available for PRO users',
      'home': 'Home',
      'statistics': 'Statistics',
      'goals': 'Goals',
      'save': 'Save',
      'cancel': 'Cancel',
      'confirm': 'Confirm',
      'update_status': 'Update Daily Status',
      'today': 'Today',
      'habits': 'Habits',
      'mood': 'Mood',
      'energy': 'Energy',
      'notes': 'Notes',
      'quick_notes': 'Quick Notes',
      'morning_brief': 'Morning Brief',
      'evening_review': 'Evening Review',
      'notifications_title': 'Notifications',
      'privacy_title': 'Privacy & Security',
      'account_title': 'Account',
      'pro_plan': 'PRO Plan',
      'personal_info': 'Personal Information',
      'biometric_lock': 'Biometric Lock',
      'analytics': 'Anonymous Analytics',
      'habit_reminders': 'Habit Reminders',
      'goal_deadlines': 'Goal Deadlines',
      'ai_insights': 'AI Insights',
      'weekly_reports': 'Weekly Reports',
      'focus_mode': 'Focus Mode',
      'milestones': 'Milestones',
      'deep_work': 'Deep Work Insights',
      'manage_habits': 'Manage Habits',
      'add_habit': 'Add Habit',
      'edit_habit': 'Edit Habit',
      'delete_habit': 'Delete Habit',
      'habit_name': 'Habit Name',
      'color': 'Color',
      'reorder': 'Drag to reorder',
      'no_habits': 'No habits tracked today',
      'stats_overview': 'Statistics Overview',
      'month': 'Month',
      'week': 'Week',
      'year': 'Year',
      'life': 'Life',
      'statistics_title': 'Statistics',
      'statistics_subtitle': 'Detailed analysis of your performance.',
      'all_habits': 'All Habits',
      'select_habit': 'SELECT HABIT',
      'tab_info': 'Info',
      'tab_trend': 'Trend',
      'tab_alert': 'Alert',
      'tab_habits': 'Habits',
      'tab_mood': 'Mood',
      'tab_stats': 'Stats',
      'completion': 'Completion',
      'global': 'Global',
      'best_streak': 'Best Streak',
      'days': 'Days',
      'top_performer': 'Top Performer',
      'critical_day': 'Critical Day',
      'focus_required': 'Focus Required',
      'key_habits': 'Key Habits',
      'key_habits_desc': 'Habits that positively influence many others',
      'high_impact': 'High Impact',
      'connections': 'connections',
      'avg_impact': 'Avg Impact',
      'correlation_analysis': 'Correlation Analysis',
      'patterns_desc': 'Patterns between your habits',
      'pairs_analyzed': 'Pairs Analyzed',
      'avg_correlation': 'Avg Correlation',
      'positive': 'Positive',
      'negative': 'Negative',
      'isolated_habits': 'Isolated Habits',
      'isolated_habits_desc': 'No significant correlations found.',
      'positive_correlations': 'Positive Correlations',
      'negative_correlations': 'Negative Correlations',
      'recent_activity': 'Recent Activity',
      'suggestion': 'Suggestion',
      'suggestion_domino': 'Key habits have a "domino" effect.',
      'completion_trend': 'Completion Trend',
      'timeframe_week_short': 'Week',
      'timeframe_month_short': 'Month',
      'timeframe_year_short': 'Year',
      'timeframe_all': 'All',
      'temporal_comparison': 'Temporal Comparison',
      'comparison_desc': 'Analyze how you are doing compared to the past.',
      'vs': 'vs',
      'improvement_areas': 'Improvement Areas',
      'improvement_areas_desc': 'Habits requiring more attention.',
      'succ': 'succ.',
      'black_day': 'BLACK DAY',
      'only': 'Only',
      'of_completion': 'of completion',
      'worst_streaks_analysis': 'Worst Streaks Analysis',
      'worst_streaks_desc': 'Analyzing negative streaks to find patterns.',
      'critical_habits': 'Critical Habits',
      'top_3_worst_streaks': 'Top 3 Worst Streaks',
      'consecutive_days': 'consecutive days',
      'failure_analysis': 'Failure Analysis',
      'recovery_patterns': 'Recovery Patterns',
      'avg_recovery_time': 'Avg Recovery Time',
      'good': 'Good',
      'fast_recoverers': 'FAST RECOVERERS',
      'performance_comparison': 'Performance Comparison',
      'attention': 'Attention',
      'practical_suggestions': 'Practical Suggestions',
      'habit_details': 'Habit Details',
      'sort_by': 'Sort by',
      'rate': 'Rate',
      'best_streak_label': 'Best Streak',
      'worst_streak_label': 'Worst Streak',
      'current_streak_label': 'Current Streak',
      'order_by': 'ORDER BY',
      'mood_energy_productivity': 'Mood & Energy vs Productivity',
      'wellbeing_habit_correlation': 'Wellbeing & habit correlation',
      'time_range_7d': '7d',
      'time_range_14d': '14d',
      'time_range_30d': '30d',
      'productivity': 'Productivity',
      'mood_sensitive': 'Mood Sensitive',
      'mood_sensitive_desc': 'These habits require a good mood to be completed.',
      'with_low_mood': 'with low mood',
      'with_high_mood': 'with high mood',
      'resilient': 'Resilient',
      'resilient_desc': 'Maintained even when mood and energy are low.',
      'mood_label': 'Mood',
      'energy_label': 'Energy',
      'stable': 'Stable',
      'suggestions': 'Suggestions',
      'mood_tip_1': 'Plan mood-sensitive habits when you feel best.',
      'mood_tip_2': 'Resilient habits are great to keep on difficult days.',
      'mood_tip_3': 'Track mood and energy for more accurate insights.',
      'current_streak_caps': 'CURRENT STREAK',
      'record_streak_caps': 'RECORD',
      'completion_caps': 'COMPLETION',
      'missed_caps': 'MISSED',
      'trend_last_30_days': 'Last 30 Days Trend',
      'completed': 'Completed',
      'not_completed': 'Not completed',
      'correlations_with': 'Correlations with',
      'how_habit_relates': 'How this habit relates to others',
      'together': 'together',
      'correlation_info': 'Positive correlations suggest habits that work well together. Negative ones indicate possible conflicts of time or energy.',
      'annual_calendar': 'Annual Calendar',
      'missed': 'Missed',
      'not_tracked': 'Not tracked',
      'performance_per_day': 'Performance per Day',
      'strongest_day_label': 'Strongest day',
      'weakest_day_label': 'Weakest day',
      'well_done_completion': 'Well done% completion',
      'only_completion': 'Only done% completion',
      'worst_negative_streak': 'Worst Negative Streak',
      'missed_consecutive_days': 'missed consecutive days',
      'started_on': 'Started on',
      'broken_streaks': 'Broken Streaks',
      'streak_of_days_broken': 'Streak of count days broken',
      'improvement_tip_1': 'Focus on Sun - it\'s your weakest day',
      'improvement_tip_2': 'Avoid prolonged breaks - your longest negative streak was 12 days',
      'improvement_tip_3': 'Goal: reach at least 70% completion to consolidate the habit',
      'track_mood_energy': 'Track your mood and energy.',
      'choose_color': 'Choose a color',
      'habit_hint': 'e.g. Drink water, Read...',
      'mood_correlation': 'Mood Correlation',
      'energy_correlation': 'Energy Correlation',
      'avg_mood_checked': 'Avg Mood (✓)',
      'avg_energy_checked': 'Avg Energy (✓)',
      'none': 'None',
      'on_10': 'of 10',
      'resilient_label': 'Resilient',
      'completed_vs_missed': 'Completed vs Missed',
      'performance_per_level': 'Performance per Level',
      'low_med_high_desc': 'Low (1-4) • Medium (5-7) • High (8-10)',
      'low': 'Low',
      'medium': 'Medium',
      'high': 'High',
      'with_mood': 'With Mood',
      'with_energy': 'With Energy',
      'analysis_based_on': 'Analysis based on count days with mood/energy data (done completed, missed missed)',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'email': 'Email',
      'phone_optional': 'Phone (Optional)',
      'success_save': 'Information saved successfully',
      'error_required': 'Required field',
      'error_email': 'Enter a valid email',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'january': 'January',
      'february': 'February',
      'march': 'March',
      'april': 'April',
      'may': 'May',
      'june': 'June',
      'july': 'July',
      'august': 'August',
      'september': 'September',
      'october': 'October',
      'november': 'November',
      'december': 'December',
    },
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ?? key;
  }
}

final l10nProvider = Provider<AppLocalizations>((ref) {
  final language = ref.watch(settingsProvider.select((s) => s.language));
  return AppLocalizations(language);
});

extension AppLocalizationsExtension on BuildContext {
  AppLocalizations get l10n => ProviderScope.containerOf(this).read(l10nProvider);
}
