// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';



const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error("Missing VITE_SUPABASE_URL or VITE_SUPABASE_ANON/VITE_SUPABASE_PUBLISHABLE_KEY in environment variables.");
}

// Fallback to prevent crash during module evaluation if keys are missing
// This allows the app to render and show an error instead of white screen
const url = SUPABASE_URL || "https://placeholder.supabase.co";
const key = SUPABASE_PUBLISHABLE_KEY || "placeholder-key";

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});